version: 2
jobs:
  build:
    working_directory: ~/scouter
    docker:
      - image: circleci/ruby:2.6.4-node
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: redis:5.0
        environment:
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache
      - run:
          name: Install Bundler
          command: gem install bundler -v 2.0.2
      - run:
          name: Bundle
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache
          paths:
            - vendor/bundle
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: bundle exec rspec --require spec_helper --color spec
